### ISSUE TITLE
hard to install for novice

### ISSUE THREAD

**Issue by clover1980** [gobolinux/LiveCD#10]
017 Much better version than 16.
Very hard for novice to install in automatic mode, almost impossible. It doesn't have such smart scripts like OpenSuse or for example MX to install (i want to use only half of disk for Linux), i've tried many times and it can't boot. Only worked after using the partition scheme made by MX, reformatting above it, sound showing some error during boot. After booting the network ethernet cable connection detected but no any connection to Internet (DHCP).
Would like more Blade Runner theming in GUI (with liquid bottom fog live desktop for powerful PCs), more tools like in blackarch and centralized installer like in MX and it will be an eye-candy.

**Comment by lucasvr** [comment]
Do you have instructions or more details on how to reproduce the installation problem you had before? I'd like to make sure that problem is fixed on 017 final. Were you trying it on a virtual machine or on a bare metal? Were you booting with BIOS compatibility mode enabled, or not? Did you have an ESP partition? Did you check the box to install a bootloader? How does your partition layout look like?
